linters:
  enable-all: true
  disable:
    - nlreturn
    - exhaustivestruct
    - godox
    - gomoddirectives

linters-settings:
  gomoddirectives:
    replace-allow-list:
      - k8s.io/client-go # Kuberentes client specific issue. See https://maelvls.dev/client-go-transitive-hell/.
